### ISSUE TITLE
organize frontend into components

### ISSUE THREAD

**Issue by aneeshaa1** [aecone/Focus_Feed#7]
Currently all of the html and css is in one place but it needs to be organized into separate components. 
These are components we can make based off what we have right now:

- Navbar
- Feed
- Follow
- Profile
- FeedPost

**Comment by annabelenko** [comment]
organized the css and js code into components
<img width="209" alt="Screenshot 2024-10-28 at 4 46 19 PM" src="https://github.com/user-attachments/assets/a485228f-e0f1-4dde-bb08-142a4f57392a">
